steps:
  - name: ":kotlin::broom: Trunk code check"
    plugins:
      - ssh://git@github.com/ROKT/trunk-buildkite-plugin.git#stable:
    agents:
      queue: ${ENG_DEFAULT}
    timeout_in_minutes: 15

  - label: ":docker: Build and Publish Builder Image"
    key: "build-builder-image"
    agents:
      queue: ${ENG_DEFAULT}
    plugins:
      - ssh://git@github.com/ROKT/docker-ecr-buildkite-plugin.git#stable:
          name: ${SERVICE_NAME}-builder
          target-region-group: hub
          default-branch: main
          repo-configuration:
            scan-on-push: true
            tags:
              service: ${SERVICE_NAME}
              team: "new-integrations"
            pull-policy:
              realms:
                - rokt
          docker-configuration:
            driver: "buildkit"
            cache-from:
              - ecr://${SERVICE_NAME}-builder:${SANITISED_BRANCH_NAME}-latest
              - ecr://${SERVICE_NAME}-builder:main-latest
            tags:
              - "${SANITISED_BRANCH_NAME}-${BUILDKITE_COMMIT}"
              - "${SANITISED_BRANCH_NAME}-latest"
            args:
              - "ssh=default"
          security:
            snyk: true

  - label: ":android: :gradle: Assemble debug"
    key: "build-uxhelper-debug"
    depends_on: "build-builder-image"
    commands:
      - ./gradlew assembleDebug
    artifact_paths:
      - "**/*.aar"
      - "**/*.apk"
    plugins:
      - docker#v5.11.0:
          image: "${ECR_HOST}/${SERVICE_NAME}-builder:${SANITISED_BRANCH_NAME}-${BUILDKITE_COMMIT}"
          user: root
    agents:
      queue: ${ENG_BK_AGENT}
    timeout_in_minutes: 25

  - label: ":android: :junit: Unit test"
    key: "unit-test-uxhelper"
    depends_on: "build-builder-image"
    commands:
      - ./gradlew testDebugUnitTest
    artifact_paths:
      - "**/build/test-results/*/*.xml"
    plugins:
      - docker#v5.11.0:
          image: "${ECR_HOST}/${SERVICE_NAME}-builder:${SANITISED_BRANCH_NAME}-${BUILDKITE_COMMIT}"
          user: root
    agents:
      queue: ${ENG_BK_AGENT}
    timeout_in_minutes: 25

  - label: ":android: :pick: Lint check"
    key: "lint-check-uxhelper"
    depends_on: "build-builder-image"
    commands:
      - ./gradlew lintRelease
    artifact_paths:
      - "**/lint-results-*.html"
    plugins:
      - docker#v5.11.0:
          image: "${ECR_HOST}/${SERVICE_NAME}-builder:${SANITISED_BRANCH_NAME}-${BUILDKITE_COMMIT}"
          user: root
    agents:
      queue: ${ENG_BK_AGENT}
    timeout_in_minutes: 25

  - wait: ~

  - input: ":whale: :maven: Publish prompt"
    prompt: "Publish the SDK to Maven?"
    key: "publish-prompt-uxhelper"
    branches: "!main !release-*"
    fields:
      - text: "Version suffix? (Eg: -rc.1, -alpha.1)"
        key: "version_suffix"
        required: true

  - label: ":maven: :rocket: Publish SDK to MavenCentral"
    key: "publish-uxhelper-feature-branch"
    depends_on:
      - "publish-prompt-uxhelper"
      - "build-builder-image"
      - "build-uxhelper-debug"
      - "unit-test-uxhelper"
      - "lint-check-uxhelper"
    branches: "!main !release-*"
    commands:
      - . ./export_env_vars.sh
      - ./gradlew publishMavenPublicationToMavenLocal
      - ./gradlew publishMavenPublicationToMavenCentralRepository --no-configuration-cache
    artifact_paths:
      - "**/build/outputs/aar/*.*"
      - "**/build/publications/maven/*.*"
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          env:
            SIGNING_KEY:
              secret-id: stage-android-sdk-buildkite
              json-key: .SIGNING_KEY
            SIGNING_PASSWORD:
              secret-id: stage-android-sdk-buildkite
              json-key: .SIGNING_PASSWORD
            SONATYPE_USERNAME:
              secret-id: stage-android-sdk-buildkite
              json-key: .SONATYPE_USERNAME
            SONATYPE_PASSWORD:
              secret-id: stage-android-sdk-buildkite
              json-key: .SONATYPE_PASSWORD
      - ecr#v2.8.0:
          login: true
          account_ids: "${ENG_ACCOUNT}"
      - docker#v5.11.0:
          image: "${ECR_HOST}/${SERVICE_NAME}-builder:${SANITISED_BRANCH_NAME}-${BUILDKITE_COMMIT}"
          user: root
          mount-buildkite-agent: true
          mount-checkout: true
          propagate-environment: true
          environment:
            - SIGNING_KEY
            - SIGNING_PASSWORD
            - SONATYPE_USERNAME
            - SONATYPE_PASSWORD
    agents:
      queue: ${STAGE_BK_AGENT}
    timeout_in_minutes: 30

  - label: ":maven: :rocket: Publish SDK to MavenCentral"
    key: "publish-uxhelper"
    depends_on:
      - "build-builder-image"
      - "build-uxhelper-debug"
      - "unit-test-uxhelper"
      - "lint-check-uxhelper"
    branches: "main release-*"
    commands:
      - . ./export_env_vars.sh
      - ./gradlew publishMavenPublicationToMavenLocal
      - ./gradlew publishMavenPublicationToMavenCentralRepository --no-configuration-cache
    soft_fail: true # Publishing to external repository may fail if the version already exists
    artifact_paths:
      - "**/build/outputs/aar/*.*"
      - "**/build/publications/maven/*.*"
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          env:
            SIGNING_KEY:
              secret-id: stage-android-sdk-buildkite
              json-key: .SIGNING_KEY
            SIGNING_PASSWORD:
              secret-id: stage-android-sdk-buildkite
              json-key: .SIGNING_PASSWORD
            SONATYPE_USERNAME:
              secret-id: stage-android-sdk-buildkite
              json-key: .SONATYPE_USERNAME
            SONATYPE_PASSWORD:
              secret-id: stage-android-sdk-buildkite
              json-key: .SONATYPE_PASSWORD
      - ecr#v2.8.0:
          login: true
          account_ids: "${ENG_ACCOUNT}"
      - docker#v5.11.0:
          image: "${ECR_HOST}/${SERVICE_NAME}-builder:${SANITISED_BRANCH_NAME}-${BUILDKITE_COMMIT}"
          user: root
          mount-buildkite-agent: true
          mount-checkout: true
          propagate-environment: true
          environment:
            - SIGNING_KEY
            - SIGNING_PASSWORD
            - SONATYPE_USERNAME
            - SONATYPE_PASSWORD
    agents:
      queue: ${STAGE_BK_AGENT}
    timeout_in_minutes: 30
