#checkov:skip=CKV_OPENAPI_4:Not required to have auth schema defs
openapi: 3.0.0
info:
  title: Rokt UX Helper Android
  x-cortex-tag: android-ux-helper
  x-cortex-type: service
  description: |
    Native Android UX Helper and demo app.
  x-cortex-git:
    github:
      repository: ROKT/rokt-ux-helper-android

  x-cortex-owners:
    - type: group
      name: sdk-engineering
      provider: CORTEX
  x-cortex-groups:
    - lang-kotlin

  x-cortex-oncall:
    opsgenie:
      type: SCHEDULE
      id: Mobile Integrations_schedule

  x-cortex-ci-cd:
    buildkite:
      pipelines:
        - slug: ux-helper-android
