name: Draft release prepare CHANGELOG

on:
  pull_request:
    paths:
      - VERSION
    types:
      - opened
    branches:
      - main

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get version name
        id: version
        run: |
          version_from_file=$(head -n 1 VERSION)
          echo "release-version=$version_from_file" >> $GITHUB_OUTPUT
      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v2
        with:
          tag: ${{ steps.version.outputs.release-version }}
      - name: Commit and push CHANGELOG.md
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG for ${{ steps.version.outputs.release-version }}"
          echo "$(git log -n 5 --oneline)"
          git push origin HEAD
